-- cdcx local development schema.
-- Runs once on first container start (docker-entrypoint-initdb.d).

-- REPLICA IDENTITY FULL so updates and deletes carry full old row images,
-- which the decoder and the M4 differential oracle both rely on.
CREATE TABLE public.users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     TEXT NOT NULL,
    email    TEXT,
    balance  NUMERIC(12, 2) NOT NULL DEFAULT 0,
    active   BOOLEAN NOT NULL DEFAULT true,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.users REPLICA IDENTITY FULL;

CREATE PUBLICATION cdcx_pub FOR TABLE public.users;
